#!/usr/bin/env python

import cbopensource.connectors.vmray.bridge as bridge
from cbopensource.connectors.vmray import __version__
import os
import sys


def main():
    name = "vmray"

    # set the path to the CA certificate PEM file to our local cache
    cacert_pem_path = "/usr/share/cb/integrations/vmray/cacert.pem"
    if os.path.isfile(cacert_pem_path):
        os.environ["REQUESTS_CA_BUNDLE"] = cacert_pem_path

    daemon = bridge.VMRayConnector(
		name,
		configfile="/etc/cb/integrations/vmray/connector.conf",
		work_directory="/usr/share/cb/integrations/vmray/db",
	)

    if len(sys.argv) == 2:
        if "start" == sys.argv[1]:
            daemon.start()
        elif "stop" == sys.argv[1]:
            daemon.stop()
        elif "restart" == sys.argv[1]:
            daemon.restart()
        elif "version" == sys.argv[1]:
            print "%s - version %s" % (name, __version__)
        else:
            print "Unknown command: %s" % (sys.argv[1])
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % (sys.argv[0])
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
	main()
